// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ics/provider/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// fees_per_block is the fee charged per block for consumer chain operation.
	FeesPerBlock types.Coin `protobuf:"bytes,1,opt,name=fees_per_block,json=feesPerBlock,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fees_per_block"`
	// downtime_slashing_window is the number of blocks in which a validator
	// can be offline before being slashed for downtime on consumer chains.
	DowntimeSlashingWindow int64 `protobuf:"varint,2,opt,name=downtime_slashing_window,json=downtimeSlashingWindow,proto3" json:"downtime_slashing_window,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20d73d2e753a911, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFeesPerBlock() types.Coin {
	if m != nil {
		return m.FeesPerBlock
	}
	return types.Coin{}
}

func (m *Params) GetDowntimeSlashingWindow() int64 {
	if m != nil {
		return m.DowntimeSlashingWindow
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "ics.provider.v1.Params")
}

func init() { proto.RegisterFile("ics/provider/v1/params.proto", fileDescriptor_b20d73d2e753a911) }

var fileDescriptor_b20d73d2e753a911 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x31, 0x4f, 0xe3, 0x30,
	0x14, 0xc7, 0xe3, 0x3b, 0xa9, 0x43, 0xae, 0xba, 0xea, 0xaa, 0x13, 0x4a, 0x2b, 0x94, 0x56, 0x4c,
	0x55, 0xa5, 0xc4, 0x0a, 0x0c, 0x20, 0xc6, 0x22, 0x31, 0x97, 0x32, 0x20, 0xb1, 0x44, 0x8e, 0x63,
	0x52, 0xab, 0x89, 0x5f, 0x14, 0xa7, 0xa9, 0xfa, 0x09, 0x90, 0x98, 0x98, 0x99, 0x18, 0x11, 0x53,
	0x3f, 0x46, 0xc7, 0x8e, 0x4c, 0x80, 0x5a, 0x89, 0xf2, 0x31, 0x50, 0x1c, 0x83, 0xba, 0xd8, 0xef,
	0xbd, 0x9f, 0xed, 0xff, 0xff, 0x3d, 0x9b, 0xfb, 0x9c, 0x4a, 0x9c, 0x66, 0x50, 0xf0, 0x90, 0x65,
	0xb8, 0xf0, 0x70, 0x4a, 0x32, 0x92, 0x48, 0x37, 0xcd, 0x20, 0x87, 0x66, 0x83, 0x53, 0x15, 0x2a,
	0xea, 0x16, 0x5e, 0xfb, 0x1f, 0x49, 0xb8, 0x00, 0xac, 0xd6, 0xea, 0x4c, 0xdb, 0xa6, 0x20, 0x13,
	0x90, 0x38, 0x20, 0x92, 0xe1, 0xc2, 0x0b, 0x58, 0x4e, 0x3c, 0x4c, 0x81, 0x0b, 0xcd, 0x5b, 0x15,
	0xf7, 0x55, 0x86, 0xab, 0x44, 0xa3, 0xff, 0x11, 0x44, 0x50, 0xd5, 0xcb, 0xa8, 0xaa, 0x1e, 0x7c,
	0x20, 0xb3, 0x36, 0x54, 0x2e, 0x9a, 0xb7, 0xc8, 0xfc, 0x7b, 0xc3, 0x98, 0xf4, 0x53, 0x96, 0xf9,
	0x41, 0x0c, 0x74, 0x62, 0xa1, 0x2e, 0xea, 0xfd, 0x39, 0x6c, 0xb9, 0xfa, 0xa1, 0x52, 0xd5, 0xd5,
	0xaa, 0xee, 0x19, 0x70, 0x31, 0x38, 0x5f, 0xbe, 0x76, 0x8c, 0xe7, 0xb7, 0x4e, 0x2f, 0xe2, 0xf9,
	0x78, 0x1a, 0xb8, 0x14, 0x12, 0xad, 0xaa, 0x37, 0x47, 0x86, 0x13, 0x9c, 0xcf, 0x53, 0x26, 0xd5,
	0x05, 0xf9, 0xb0, 0x5d, 0xf4, 0xeb, 0x31, 0x8b, 0x08, 0x9d, 0xfb, 0xa5, 0x6f, 0xf9, 0xb4, 0x5d,
	0xf4, 0xd1, 0xa8, 0x5e, 0x0a, 0x0f, 0x59, 0x36, 0x28, 0x65, 0x9b, 0x27, 0xa6, 0x15, 0xc2, 0x4c,
	0xe4, 0x3c, 0x61, 0xbe, 0x8c, 0x89, 0x1c, 0x73, 0x11, 0xf9, 0x33, 0x2e, 0x42, 0x98, 0x59, 0xbf,
	0xba, 0xa8, 0xf7, 0x7b, 0xb4, 0xf7, 0xcd, 0x2f, 0x35, 0xbe, 0x52, 0xf4, 0xd4, 0xfa, 0x7c, 0xec,
	0xa0, 0xbb, 0xed, 0xa2, 0xdf, 0xf8, 0x19, 0x73, 0xd5, 0xdd, 0xe0, 0x62, 0xb9, 0xb6, 0xd1, 0x6a,
	0x6d, 0xa3, 0xf7, 0xb5, 0x8d, 0xee, 0x37, 0xb6, 0xb1, 0xda, 0xd8, 0xc6, 0xcb, 0xc6, 0x36, 0xae,
	0x8f, 0x77, 0xbc, 0x93, 0x1c, 0x12, 0x10, 0xcc, 0x19, 0x4f, 0x03, 0xcc, 0xa9, 0x74, 0x52, 0xa0,
	0x8e, 0x87, 0x13, 0x08, 0xa7, 0x31, 0xdb, 0xf9, 0x3a, 0xd5, 0x50, 0x50, 0x53, 0x23, 0x3c, 0xfa,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x68, 0x3a, 0xa2, 0xd7, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.FeesPerBlock.Equal(&that1.FeesPerBlock) {
		return false
	}
	if this.DowntimeSlashingWindow != that1.DowntimeSlashingWindow {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DowntimeSlashingWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DowntimeSlashingWindow))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.FeesPerBlock.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FeesPerBlock.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.DowntimeSlashingWindow != 0 {
		n += 1 + sovParams(uint64(m.DowntimeSlashingWindow))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeesPerBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeesPerBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DowntimeSlashingWindow", wireType)
			}
			m.DowntimeSlashingWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DowntimeSlashingWindow |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
