// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ics/provider/v1/provider.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConsumerStatus defines the status of a consumer chain.
type ConsumerStatus int32

const (
	// CONSUMER_STATUS_UNSPECIFIED defines an unknown status.
	ConsumerStatus_CONSUMER_STATUS_UNSPECIFIED ConsumerStatus = 0
	// CONSUMER_STATUS_PENDING defines a consumer chain that is scheduled to start.
	ConsumerStatus_CONSUMER_STATUS_PENDING ConsumerStatus = 1
	// CONSUMER_STATUS_ACTIVE defines a consumer chain that is currently active.
	ConsumerStatus_CONSUMER_STATUS_ACTIVE ConsumerStatus = 2
	// CONSUMER_STATUS_SUNSET defines a consumer chain that is scheduled to be removed.
	ConsumerStatus_CONSUMER_STATUS_SUNSET ConsumerStatus = 3
	// CONSUMER_STATUS_REMOVED defines a consumer chain that has been removed.
	ConsumerStatus_CONSUMER_STATUS_REMOVED ConsumerStatus = 4
	// CONSUMER_STATUS_OVERDUE defines a consumer state in which fees were not paid due to insufficient funds.
	ConsumerStatus_CONSUMER_STATUS_OVERDUE ConsumerStatus = 5
)

var ConsumerStatus_name = map[int32]string{
	0: "CONSUMER_STATUS_UNSPECIFIED",
	1: "CONSUMER_STATUS_PENDING",
	2: "CONSUMER_STATUS_ACTIVE",
	3: "CONSUMER_STATUS_SUNSET",
	4: "CONSUMER_STATUS_REMOVED",
	5: "CONSUMER_STATUS_OVERDUE",
}

var ConsumerStatus_value = map[string]int32{
	"CONSUMER_STATUS_UNSPECIFIED": 0,
	"CONSUMER_STATUS_PENDING":     1,
	"CONSUMER_STATUS_ACTIVE":      2,
	"CONSUMER_STATUS_SUNSET":      3,
	"CONSUMER_STATUS_REMOVED":     4,
	"CONSUMER_STATUS_OVERDUE":     5,
}

func (x ConsumerStatus) String() string {
	return proto.EnumName(ConsumerStatus_name, int32(x))
}

func (ConsumerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cbed533f3fe8d5a, []int{0}
}

// ConsumerChain represents a consumer chain registered with the provider.
type ConsumerChain struct {
	// chain_id is the chain ID of the consumer chain.
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// name is the human-readable name of the consumer chain.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// version is the version of the consumer chain software.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// status indicates the current status of the consumer chain.
	Status ConsumerStatus `protobuf:"varint,4,opt,name=status,proto3,enum=ics.provider.v1.ConsumerStatus" json:"status,omitempty"`
	// added_at is the block height at which the consumer was added.
	AddedAt int64 `protobuf:"varint,5,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	// sunset_at is the block height at which the consumer will be sunset (0 if not scheduled).
	SunsetAt int64 `protobuf:"varint,6,opt,name=sunset_at,json=sunsetAt,proto3" json:"sunset_at,omitempty"`
	// module_account_address is the address of the module account for this consumer.
	ModuleAccountAddress string `protobuf:"bytes,7,opt,name=module_account_address,json=moduleAccountAddress,proto3" json:"module_account_address,omitempty"`
}

func (m *ConsumerChain) Reset()         { *m = ConsumerChain{} }
func (m *ConsumerChain) String() string { return proto.CompactTextString(m) }
func (*ConsumerChain) ProtoMessage()    {}
func (*ConsumerChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cbed533f3fe8d5a, []int{0}
}
func (m *ConsumerChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerChain.Merge(m, src)
}
func (m *ConsumerChain) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerChain) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerChain.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerChain proto.InternalMessageInfo

func (m *ConsumerChain) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ConsumerChain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConsumerChain) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConsumerChain) GetStatus() ConsumerStatus {
	if m != nil {
		return m.Status
	}
	return ConsumerStatus_CONSUMER_STATUS_UNSPECIFIED
}

func (m *ConsumerChain) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

func (m *ConsumerChain) GetSunsetAt() int64 {
	if m != nil {
		return m.SunsetAt
	}
	return 0
}

func (m *ConsumerChain) GetModuleAccountAddress() string {
	if m != nil {
		return m.ModuleAccountAddress
	}
	return ""
}

func init() {
	proto.RegisterEnum("ics.provider.v1.ConsumerStatus", ConsumerStatus_name, ConsumerStatus_value)
	proto.RegisterType((*ConsumerChain)(nil), "ics.provider.v1.ConsumerChain")
}

func init() { proto.RegisterFile("ics/provider/v1/provider.proto", fileDescriptor_6cbed533f3fe8d5a) }

var fileDescriptor_6cbed533f3fe8d5a = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x8a, 0xd3, 0x40,
	0x1c, 0xc6, 0x3b, 0x6d, 0xb7, 0xdd, 0x1d, 0x70, 0x8d, 0xc3, 0xb2, 0xc6, 0x16, 0xd2, 0xe2, 0xa9,
	0x08, 0x4d, 0xa8, 0x0a, 0x0b, 0xde, 0x62, 0x3a, 0x4a, 0x0e, 0x9b, 0xae, 0x49, 0xd3, 0x83, 0x97,
	0x30, 0xcd, 0x0c, 0xed, 0x80, 0xc9, 0x94, 0xcc, 0xa4, 0xe0, 0x03, 0x78, 0xf7, 0x11, 0x7c, 0x14,
	0x8f, 0x1e, 0xf7, 0xe8, 0x51, 0xda, 0x8b, 0x8f, 0x21, 0x99, 0xac, 0x45, 0x4b, 0x2f, 0xc3, 0xf7,
	0xff, 0x7e, 0x1f, 0x33, 0x1f, 0xc3, 0x1f, 0x5a, 0x3c, 0x95, 0xce, 0xa6, 0x10, 0x5b, 0x4e, 0x59,
	0xe1, 0x6c, 0x27, 0x07, 0x6d, 0x6f, 0x0a, 0xa1, 0x04, 0x7a, 0xcc, 0x53, 0x69, 0x1f, 0xbc, 0xed,
	0xa4, 0xf7, 0x84, 0x64, 0x3c, 0x17, 0x8e, 0x3e, 0xeb, 0x4c, 0xef, 0x6a, 0x25, 0x56, 0x42, 0x4b,
	0xa7, 0x52, 0xb5, 0xfb, 0xfc, 0x4b, 0x13, 0x3e, 0xf2, 0x44, 0x2e, 0xcb, 0x8c, 0x15, 0xde, 0x9a,
	0xf0, 0x1c, 0x3d, 0x83, 0xe7, 0x69, 0x25, 0x12, 0x4e, 0x4d, 0x30, 0x04, 0xa3, 0x8b, 0xb0, 0xab,
	0x67, 0x9f, 0x22, 0x04, 0xdb, 0x39, 0xc9, 0x98, 0xd9, 0xd4, 0xb6, 0xd6, 0xc8, 0x84, 0xdd, 0x2d,
	0x2b, 0x24, 0x17, 0xb9, 0xd9, 0xaa, 0xd3, 0x0f, 0x23, 0xba, 0x81, 0x1d, 0xa9, 0x88, 0x2a, 0xa5,
	0xd9, 0x1e, 0x82, 0xd1, 0xe5, 0xcb, 0x81, 0x7d, 0xd4, 0xd2, 0xfe, 0xfb, 0x70, 0xa4, 0x63, 0xe1,
	0x43, 0xbc, 0x6a, 0x40, 0x28, 0x65, 0x34, 0x21, 0xca, 0x3c, 0x1b, 0x82, 0x51, 0x2b, 0xec, 0xea,
	0xd9, 0x55, 0xa8, 0x0f, 0x2f, 0x64, 0x99, 0x4b, 0xa6, 0x2a, 0xd6, 0xd1, 0xec, 0xbc, 0x36, 0x5c,
	0x85, 0x5e, 0xc3, 0xeb, 0x4c, 0xd0, 0xf2, 0x13, 0x4b, 0x48, 0x9a, 0x8a, 0x32, 0x57, 0x09, 0xa1,
	0xb4, 0x60, 0x52, 0x9a, 0x5d, 0xdd, 0xec, 0xaa, 0xa6, 0x6e, 0x0d, 0xdd, 0x9a, 0xbd, 0x69, 0xff,
	0xfe, 0x36, 0x00, 0x2f, 0xbe, 0x03, 0x78, 0xf9, 0x7f, 0x1d, 0x34, 0x80, 0x7d, 0x6f, 0x16, 0x44,
	0xf1, 0x2d, 0x0e, 0x93, 0x68, 0xee, 0xce, 0xe3, 0x28, 0x89, 0x83, 0xe8, 0x0e, 0x7b, 0xfe, 0x3b,
	0x1f, 0x4f, 0x8d, 0x06, 0xea, 0xc3, 0xa7, 0xc7, 0x81, 0x3b, 0x1c, 0x4c, 0xfd, 0xe0, 0xbd, 0x01,
	0x50, 0x0f, 0x5e, 0x1f, 0x43, 0xd7, 0x9b, 0xfb, 0x0b, 0x6c, 0x34, 0x4f, 0xb1, 0x28, 0x0e, 0x22,
	0x3c, 0x37, 0x5a, 0xa7, 0x2e, 0x0d, 0xf1, 0xed, 0x6c, 0x81, 0xa7, 0x46, 0xfb, 0x14, 0x9c, 0x2d,
	0x70, 0x38, 0x8d, 0xb1, 0x71, 0xf6, 0xf6, 0xc3, 0x8f, 0x9d, 0x05, 0xee, 0x77, 0x16, 0xf8, 0xb5,
	0xb3, 0xc0, 0xd7, 0xbd, 0xd5, 0xb8, 0xdf, 0x5b, 0x8d, 0x9f, 0x7b, 0xab, 0xf1, 0xf1, 0x66, 0xc5,
	0xd5, 0xba, 0x5c, 0xda, 0xa9, 0xc8, 0x1c, 0xa2, 0x44, 0x26, 0x72, 0x36, 0x5e, 0x97, 0x4b, 0x87,
	0xa7, 0x72, 0xbc, 0x11, 0xe9, 0x78, 0xe2, 0xd4, 0x3f, 0xf3, 0xcf, 0x8e, 0xa9, 0xcf, 0x1b, 0x26,
	0x97, 0x1d, 0xbd, 0x24, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x8b, 0x98, 0x6b, 0x80,
	0x02, 0x00, 0x00,
}

func (this *ConsumerChain) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ConsumerChain)
	if !ok {
		that2, ok := that.(ConsumerChain)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ChainId != that1.ChainId {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.AddedAt != that1.AddedAt {
		return false
	}
	if this.SunsetAt != that1.SunsetAt {
		return false
	}
	if this.ModuleAccountAddress != that1.ModuleAccountAddress {
		return false
	}
	return true
}
func (m *ConsumerChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModuleAccountAddress) > 0 {
		i -= len(m.ModuleAccountAddress)
		copy(dAtA[i:], m.ModuleAccountAddress)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.ModuleAccountAddress)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SunsetAt != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.SunsetAt))
		i--
		dAtA[i] = 0x30
	}
	if m.AddedAt != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.AddedAt))
		i--
		dAtA[i] = 0x28
	}
	if m.Status != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProvider(dAtA []byte, offset int, v uint64) int {
	offset -= sovProvider(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConsumerChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovProvider(uint64(m.Status))
	}
	if m.AddedAt != 0 {
		n += 1 + sovProvider(uint64(m.AddedAt))
	}
	if m.SunsetAt != 0 {
		n += 1 + sovProvider(uint64(m.SunsetAt))
	}
	l = len(m.ModuleAccountAddress)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	return n
}

func sovProvider(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProvider(x uint64) (n int) {
	return sovProvider(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConsumerChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProvider
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ConsumerStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedAt", wireType)
			}
			m.AddedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AddedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SunsetAt", wireType)
			}
			m.SunsetAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SunsetAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProvider(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProvider
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProvider(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProvider
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProvider
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProvider
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProvider
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProvider        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProvider          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProvider = fmt.Errorf("proto: unexpected end of group")
)
